### ISSUE TITLE
Release script creates binary by invalid name.

### ISSUE THREAD

**Issue by nbering** [nbering/terraform-provider-ansible#2]
The plugin filename convention was inaccurately documented by Terraform, so the "helpful" file name I used for the release binary filenames is incorrect. The dash(`-`) between the plugin name and the version number should be an underscore(`_`).

https://github.com/hashicorp/terraform/issues/15705

**Comment by imchairmanm** [comment]
Thanks for opening this! I had a bit of trouble trying to figure out why Terraform was unable to find the plugin.  I didn't think to look at the binary name.

Also, just wanted to say that this approach has been working really well for me.  Thank you for providing the tools and for writing up the blog post on them!

**Comment by nbering** [comment]
Thanks @imchairmanm! There's a fair bit of traffic coming to the blog post and Repo. I have a little vacation time coming up, so I may do some further clean-up and documentation while I have the time.

Clearing up this issue would be included in that effort.

**Comment by nbering** [comment]
Re-opening until I get a new release builds attached to the GitHub release.

**Comment by nbering** [comment]
Closing again... should be fixed in archives attached to [v0.0.2](https://github.com/nbering/terraform-provider-ansible/releases/tag/v0.0.2).

v0.0.2 is functionally equivalent to v0.0.1, except that the release build process has been improved.
