### ISSUE TITLE
Compile as static binary?

### ISSUE THREAD

**Issue by rgevaert** [nbering/terraform-provider-ansible#27]
Hi

would it be possible to make the binary available as a static binary? This will make it possible to run the provider in alpine based docker images (i.e. https://hub.docker.com/r/hashicorp/terraform).

Thanks in advance,

Rudy

**Comment by rgevaert** [comment]
Nevermind, v0.0.4 was dynamically compiled, v0.0.6 not anymore ;)

**Comment by nbering** [comment]
I'm glad that worked out for you. v0.0.4 was probably compiled with an older version of Go.
