### ISSUE TITLE
Publish provider for use in Terraform 0.13

### ISSUE THREAD

**Issue by paultyng** [nbering/terraform-provider-ansible#29]
👋 Hi, I'm on the Terraform Providers team at HashiCorp. With the [release of the Terraform 0.13 beta](https://discuss.hashicorp.com/t/terraform-0-13-beta-released/9555), users can now download and install community providers from the registry. We are inviting provider authors (especially those for popular community providers) to publish their providers in a closed beta.

To get invited to the closed beta, please email terraform-registry-beta@hashicorp.com. We need:

- A list of GitHub usernames to add to the beta (you and any team members who will publish)
- List of provider repositories you plan to publish
- A GPG public key in ASCII-armor format, which you will be using to sign your provider releases

You can use one key for all of your providers, or separate keys if you prefer. If you are publishing from an organization, this key or keys will be associated with that namespace. Once in the beta, you can manage personal keys in the UI as well.

**Comment by nbering** [comment]
@paultyng Thank you! I haven't been keeping apace with the latest in a while (Terraform development is just moving too fast compared to when I started tracking it at v0.9.x). I love that you're providing a solution for this! ❤️

**Comment by nbering** [comment]
Planning to follow up on this within the week.

**Comment by rgl** [comment]
Terraform 0.13 is now out in the wild ;-)

**Comment by rgl** [comment]
As a side-node, if anyone wants to try this provider with terraform 0.13, you can do it like I did in https://github.com/rgl/terraform-ansible-azure-vagrant/commit/2dfbcbaa2e8c65bc0196e7a194e463bd37a56340. It works fine without recompiling this provider.

**Comment by nbering** [comment]
Sorry for the delay on this. I haven't had a lot of time for my OSS side-projects lately. Registering with the Hashicorp is still on my TODO list.

**Comment by paultyng** [comment]
👍 Let me know if there is anything I can do to help. This should be self-serve now in the registry UI, you just need to create releases that conform to the [publishing criteria](https://www.terraform.io/docs/registry/providers/publishing.html) (we have a [goreleaser](https://github.com/hashicorp/terraform-provider-scaffolding/blob/master/.goreleaser.yml) config file that can do it).

**Comment by nbering** [comment]
Since everyone's complaining about the registry thing but no one says 1.0.3 didn't work with Terraform 0.13... I presumed no changes were needed, but that a compatible release with signatures was required.

I've cut a new version - v1.0.4 - with goreleaser, and it's been added to the releases section. The provider is also been registered with Hashicorp's site. Hope this helps everyone!

**Comment by rgl** [comment]
Strange, 1.0.3 is working for me with terraform 0.13 when installed locally.

What do you mean by signatures? It needs the sha256sums file signed?

Please bear in mind that I know nothing about the terraform registry publication... Did you have to upload anything there? Or do you only need link to this github repository?
