### ISSUE TITLE
Submit this provider to Terraform Registry

### ISSUE THREAD

**Issue by jakubgs** [nbering/terraform-provider-ansible#31]
Now that `0.13.0` is out Terrform supports [Explicit Provider Source Locations](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations), which means it can install providers available in the [Terraform Registry](https://registry.terraform.io/).

It would make it simpler to use this provider if it was available there.

**Comment by nbering** [comment]
Duplicate of #29
