### ISSUE TITLE
Run ansible as part of Terraform rollout

### ISSUE THREAD

**Issue by DanielMSchmidt** [nbering/terraform-provider-ansible#36]
This is probably out of scope for this project but I wanted to explore this idea:

Could we add this feature to the provider:

```tf
resource "ansible_host" "example" {
    inventory_hostname = "example.com"
    groups = ["web"]
    vars = {
        ansible_user = "admin"
    }
}

resource "ansible_provisioning" "web" {
  hosts = [ansible_host.example]
  galaxy_roles = file("${path.module}/requirements.txt")
  playbook = file("${path.module}/web.yaml")
}
```

If one uses a reference to the cloud resource as input for ansible_host the ansible provisioning could be deferred until the resource is up.

Feel free to close if this is way out of scope :)

**Comment by nbering** [comment]
Addressed in duplicate, #35.
