### ISSUE TITLE
Creating the host list from modules

### ISSUE THREAD

**Issue by prandelicious** [nbering/terraform-provider-ansible#9]
I have a bunch of EC2 instances created via a module. I can get the list of internal IP addresses of these instances. How do I declare this in the *ansible_host* resource?

**Comment by nbering** [comment]
The `ansible_host` resource can exist inside the module, and the [inventory script](https://github.com/nbering/terraform-inventory) will still be able to find it. If it doesn't that would be a bug.

If you don't want the `ansible_host` to be inside the module, then you will need to configure an [output](https://www.terraform.io/intro/getting-started/modules.html#module-outputs) from the module.

**Comment by nbering** [comment]
@prandelicious, if this is still relevant to you, just provide more information and I'll re-open.
